config/routes.rb
RunWithMe::Application.routes.draw do
  devise_for :users

  root to: "home#index"
  
  resources :users, :races, :messages

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender
  belongs_to :reciever
end

app/models/participant.rb
class Participant < ActiveRecord::Base
end

app/models/race.rb
class Race < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :race_name
  validates_presence_of :time_minute
  validates_presence_of :distance
  validates :time_second, :numericality => { :greater_than => -1, :less_than_or_equal_to => 59 }
  validates :time_minute, :numericality => { :greater_than => -1 }


  def format_time
    "#{time_minute}:#{time_second}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :races
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :encrypted_password
  validates :time_running, numericality: :true
  validates :average_pace_second, numericality: :true
  validates_presence_of :average_pace_second
  validates_presence_of :average_pace_minute, numericality: :true
  validates :distance_per_week, numericality: :true
  validates :distance_per_week, :numericality => { :greater_than => 0 }
  validates :average_pace_second, :numericality => { :greater_than => -1, :less_than_or_equal_to => 59 }
  validates :average_pace_minute, numericality: :true
  has_many :messages, :as => :reciever
  has_many :messages, :as => :sender
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:first_name, :last_name, :email, :password, 
    :encrypted_password, :distance_per_week, :average_pace_second, :average_pace_minute, :time_running )}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @user = current_user
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/races_controller.rb
class RacesController < ApplicationController

  def index
  end

  def new
    @race = Race.new
    @race_distances = ["5k", "10k", "Half Marathon", "Marthon"]
  end

  def create
    @race = current_user.races.build(race_params)
    if @race.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def race_params
    params.require(:race).permit(:race_name, :distance, :time_second, :time_minute, :location)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :validate_user, :only => :show

  def edit
    @user = current_user
  end

  def index
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:saved]="Saved"
      redirect_to  user_path
    else
      render action: 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @all_users = User.all
  end

  def validate_user
    redirect_to root_path unless current_user.id.to_s == params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="twelve columns text-center">
  <h1>Welcome to Run with Me</h1>
    <% if !user_signed_in? %>
      <%=link_to "Join", new_user_registration_path, class: "button"%>
    <%else%>
      <%= link_to 'Profile', user_path(@user), class: "button" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" style="background-color:#01DFA5">
      <ul class="title-area">
        <li class="name">
          <div>
        <h1><%= link_to "Run With Me", root_path %></h1>
          </div>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <% if user_signed_in? %>
          <li class="divider">
          <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          <%else %>
          <li class="divider"></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Sign in",new_user_session_path %></li>
          <% end %>
        </ul>
    </nav>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/races/new.html.erb
<br>
<div class="row">
  <div class="small-2 large-4 columns">
    <%= simple_form_for @race do |f|%>
      <%= f.input :race_name, label: 'Race Name'%>
      <%= f.input :distance, collection: @race_distances, label: 'Distance' %>
    <h5>Race Time</h5>
      <%= f.input :time_minute, label:'Minutes'%>
      <%= f.input :time_second, label:'Seconds' %>
      <%= f.input :location, label: 'Location' %>
      <%= f.button :submit ,class: "button"%>
  <% end %>
</div>
</div>

app/views/users/index.html.erb
<div class="row">
   <div class="medium-6 columns">
    <h1><%= @user.first_name %><%= @user.last_name %></h1>
  </div>
</div>
<div class="row">
   <div class="medium-6 columns">
    <%= link_to "Add New Race", new_race_path %>
    <br>
    <%= link_to "Find People to Run With", users_path %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
   <div class="medium-6 columns">
    <h1><%= @user.first_name %><%= @user.last_name %></h1>
  </div>
</div>
<div class="row">
   <div class="medium-6 columns">
    <%= link_to "Add New Race", new_race_path %>
    <br>
    <%= link_to "Find People to Run With", users_path %>
  </div>
</div>

<div class="row">
   <div class="medium-3 columns">
  </div>
</div>
<br>
<div class="row">
  <div class-"small-6 large-centered columns">
    <table border="1">
      <tr>
    <th>Race</th>
    <th>Distance</th>
    <th>Time</th>
    <th>Location</th>
      <tr>
        <% @user.races.each do |race| %>
        <td><%= race.race_name %></td>
        <td><%= race.distance %></td>
        <td><%= race.format_time %></td>
          <% if race.location != nil %>
            <td><%= race.location %></td>
          <% else %>
            <td>No Location<td>
          <% end %>
      </tr>
        <% end %>
    </table>
  </div>
</div>